version = 0.1

[default.global.parameters]
stack_name = "cross-account-events"

[default.build.parameters]
cached = true
parallel = true
beta_features = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "eu-north-1"

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true
beta_features = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
