version = 0.1

[default.global.parameters]
stack_name = "store-and-serve-large-media-files"

[default.build.parameters]
cached = true
parallel = true
beta_features = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "store-and-serve-large-media-files"
region = "eu-north-1"
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true
beta_features = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
