[package]
name = "storage-first"
version = "0.1.0"
edition = "2021"

[dependencies]
aws_lambda_events = "0.15.1"
lambda_runtime = "0.13.0"
tokio = { version = "1", features = ["macros"] }

[[bin]]
name = "notification"
path = "src/notification.rs"
